### ISSUE TITLE
Добавить shareable google календарик

### ISSUE THREAD

**Issue by sadfuzzy** [moscowrb/organisation#2]
Добавить shareable google календарик, чтобы в телефоне была напоминалка о встрече. Возможно, на http://www.meetup.com/ добавиться тоже.

**Comment by davydovanton** [comment]
о, хорошая идея, спасибо!

**Comment by davydovanton** [comment]
Сделал, ссылка тут
https://calendar.google.com/calendar/embed?src=tnbun5jitv115qok8vi48tbg9g%40group.calendar.google.com&ctz=Europe/Moscow
