### ISSUE TITLE
Конкурс: railsclub 2k17

### ISSUE THREAD

**Issue by davydovanton** [moscowrb/organisation#3]
https://t.me/pepegramming/53

**Comment by Mehonoshin** [comment]
Адское количество метапрограммирования и Rails гномиков

**Comment by shiroginne** [comment]
Hardiest problem ever in my work: issues in GitHub without description 
(proof) :trollface: 
![screen shot 2017-09-11 at 12 54 26](https://user-images.githubusercontent.com/63340/30273528-a72e0ca4-96f9-11e7-9f33-5db52abaeb88.png)

**Comment by kirill-fedyanin** [comment]
Если всё раскладывать по solid - получается большой уровень вложенности зависимостей. Если не раскладывать - то начинается трэш с god objects

**Comment by kirill-fedyanin** [comment]
Количество болйерплейта в реакте зашкаливает

**Comment by killthekitten** [comment]
Я перехожу из веба в дата саенс, а сегодня это автоматически значит, что я становлюсь программистом на питоне. Он хорош (за это я не получу лайков, знаю), но руби ведь тоже старается: https://github.com/arbox/machine-learning-with-ruby

В руби нет такой экосистемы, как [scipy](https://www.scipy.org/) в питоне. Никаких серьезных причин, кроме исторических, я для этого не вижу. Вот такая у меня боль.

Рано или поздно вам придется подсесть на иглу машинного обучения, поэтому можно начать прямо сейчас: https://www.youtube.com/watch?v=T1nFQ49TyeA

Если каждый из будущих комментаторов перенесет по одному методу из [sklearn](http://scikit-learn.org/) в руби, этот мир станет гораздо лучше.

**Comment by X1ting** [comment]
<img width="400" alt="subl" src="https://user-images.githubusercontent.com/8531110/30272977-b0899a1a-96ff-11e7-825e-86b71f2875a7.png">

**Comment by vovs03** [comment]
"Пересадка мозга" из мира Windows-systems в мир опен-сорсных Linux-systems.

**Comment by domenic99** [comment]
Распределение кода по папкам, а потом борьба с неймспейсами
